// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VotacionNacional.DAL.Context;

#nullable disable

namespace VotacionNacional.DAL.Migrations
{
    [DbContext(typeof(VotacionDbContext))]
    [Migration("20260725211227_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VotacionNacional.DAL.Entities.Partido", b =>
                {
                    b.Property<int>("PartidoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PartidoId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("ImagenUrl")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Siglas")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("PartidoId");

                    b.HasIndex("Siglas")
                        .IsUnique();

                    b.ToTable("Partidos");
                });

            modelBuilder.Entity("VotacionNacional.DAL.Entities.Votante", b =>
                {
                    b.Property<int>("VotanteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VotanteId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PrimerApellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SegundoApellido")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("VotanteId");

                    b.HasIndex("Cedula")
                        .IsUnique();

                    b.ToTable("Votantes");
                });

            modelBuilder.Entity("VotacionNacional.DAL.Entities.Voto", b =>
                {
                    b.Property<int>("VotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VotoId"));

                    b.Property<DateTime>("FechaVoto")
                        .HasColumnType("datetime2");

                    b.Property<int>("PartidoId")
                        .HasColumnType("int");

                    b.Property<int>("VotanteId")
                        .HasColumnType("int");

                    b.HasKey("VotoId");

                    b.HasIndex("PartidoId");

                    b.HasIndex("VotanteId")
                        .IsUnique();

                    b.ToTable("Votos");
                });

            modelBuilder.Entity("VotacionNacional.DAL.Entities.Voto", b =>
                {
                    b.HasOne("VotacionNacional.DAL.Entities.Partido", "Partido")
                        .WithMany("Votos")
                        .HasForeignKey("PartidoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VotacionNacional.DAL.Entities.Votante", "Votante")
                        .WithOne("Voto")
                        .HasForeignKey("VotacionNacional.DAL.Entities.Voto", "VotanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Partido");

                    b.Navigation("Votante");
                });

            modelBuilder.Entity("VotacionNacional.DAL.Entities.Partido", b =>
                {
                    b.Navigation("Votos");
                });

            modelBuilder.Entity("VotacionNacional.DAL.Entities.Votante", b =>
                {
                    b.Navigation("Voto");
                });
#pragma warning restore 612, 618
        }
    }
}
